import Footer from '@/pages/components/Footer'
import Navbar from '@/pages/components/Navbar'
import Head from 'next/head'
import React from 'react'

export default function MainLayout({ children }:any) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Navbar />
      <main className='h-full'>{children}</main>
      <Footer />
    </>
  )
}
